apiVersion: v1
kind: Service
metadata:
  name: postgres
  namespace: postgres  # Specify the desired namespace here
spec:
  type: {{ .Values.postgres.serviceType }}
  ports:
  - port: 5432
    targetPort: 5432
  selector:
    app: postgres
