apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: postgres-ingress
  namespace: postgres  # ✅ Move out of default namespace
  annotations:
    kubernetes.io/ingress.class: nginx  # Ensure Nginx ingress controller is installed
spec:
  rules:
  - host: {{ .Values.postgres.ingress.host }}  # Ensure this is properly defined in your values.yaml
    http:
      paths:
      - path: /  # Adjust if you need to specify different paths for routing
        pathType: Prefix
        backend:
          service:
            name: postgres  # The name of the PostgreSQL service
            port:
              number: 5432  # Ensure this matches the port of your PostgreSQL service
