apiVersion: v1
kind: PersistentVolume
metadata:
  name: postgres-pv-new
  labels:
    app: postgres
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: ""  # <-- key change here
  hostPath:
    path: /mnt/postgres-data
