apiVersion: apps/v1
kind: Deployment
metadata:
  name: vault
  namespace: vault
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vault
  template:
    metadata:
      labels:
        app: vault
    spec:
      serviceAccountName: vault-sa
      automountServiceAccountToken: false
      initContainers:
        - name: fix-permissions
          image: busybox
          command: ["sh", "-c", "mkdir -p /mnt/vault-data && chown -R 1000:1000 /mnt/vault-data"]
          volumeMounts:
            - name: vault-storage
              mountPath: /mnt/vault-data
      containers:
        - name: vault
          image: hashicorp/vault:1.15.0
          imagePullPolicy: IfNotPresent
          args:
            - server
            - '-config=/vault/config/vault.hcl'
          env:
            - name: VAULT_API_ADDR
              value: http://0.0.0.0:8200
            - name: VAULT_ADDR
              value: http://127.0.0.1:8200
            - name: VAULT_USER
              value: vaultuser
            - name: VAULT_PASSWORD
              value: vaultpass
          ports:
            - containerPort: 8200
          volumeMounts:
            - name: vault-storage
              mountPath: /vault/data
            - name: config
              mountPath: /vault/config/vault.hcl  # Specify file path directly
              subPath: vault.hcl  # Mount only the file, not a directory
          resources:
            requests:
              memory: "512Mi"
              cpu: "500m"
            limits:
              memory: "1Gi"
              cpu: "1"
          livenessProbe:
            httpGet:
              path: /v1/sys/health?standbyok=true&sealedcode=200
              port: 8200
            initialDelaySeconds: 180
            periodSeconds: 20
          readinessProbe:
            httpGet:
              path: /v1/sys/health?standbyok=true&sealedcode=200
              port: 8200
            initialDelaySeconds: 180
            periodSeconds: 20
          securityContext:
            runAsUser: 1000
            runAsGroup: 1000
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
      volumes:
        - name: vault-storage
          hostPath:
            path: /mnt/vault-data  # Path on the host node for Vault storage
            type: DirectoryOrCreate  # Create the directory if it doesn't exist
        - name: config
          configMap:
            name: vault-config  # Reference your Vault config map
            items:
              - key: vault.hcl
                path: vault.hcl  # Mount the file correctly into the container
