apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: vault-pvc-new
  namespace: vault  # add if your PVC is in 'vault' namespace
  labels:
    app: vault
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: ""  # Must match the PV's empty storageClass
  volumeMode: Filesystem
