apiVersion: v1
kind: PersistentVolume
metadata:
  name: vault-pv-new
spec:
  capacity:
    storage: 1Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: gp3-csi
  csi:
    driver: ebs.csi.aws.com
    volumeHandle: vol-00a3ac12b62001b03  # Your actual EBS Volume ID
    fsType: ext4
