apiVersion: v1
kind: ConfigMap
metadata:
  name: vault-config
  namespace: vault
data:
  vault.hcl: |
    storage "postgresql" {
      connection_url = "postgresql://vaultuser:vaultpassword@postgres:5432/vault_db?sslmode=disable"
    }

    listener "tcp" {
      address     = "0.0.0.0:8200"
      tls_disable = 1
    }

    disable_mlock = true

    seal "awskms" {
      region = "us-west-2"
      kms_key_id = "your-kms-key-id"  # Replace with your actual AWS KMS key ID
    }

    ui = true
