apiVersion: v1
kind: ConfigMap
metadata:
  name: vault-agent-config
  namespace: vault
data:
  vault-agent-config.hcl: |
    exit_after_auth = false
    pid_file = "/mnt/data/vault-agent/pidfile"

    auto_auth {
      method {
        type = "kubernetes"
        mount_path = "auth/kubernetes"
        config = {
          role = "vault-role"
        }
      }

      sink {
        type = "file"
        config = {
          path = "/mnt/data/vault-agent/token"
        }
      }
    }

    cache {
      use_auto_auth_token = true
    }

    listener "tcp" {
      address = "0.0.0.0:8200"
      tls_disable = true
    }
