apiVersion: v1
kind: Service
metadata:
  name: vault
  namespace: vault
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: "nlb"  # Specify NLB type
spec:
  selector:
    app: vault
  ports:
    - protocol: TCP
      port: 8200
      targetPort: 8200
  type: LoadBalancer  # Still use LoadBalancer type for NLB
