apiVersion: v1
kind: Service
metadata:
  name: vault
  namespace: vault  # ✅ Add the namespace here
spec:
  type: {{ .Values.vault.serviceType }}
  ports:
  - port: 8200
    targetPort: 8200
  selector:
    app: vault
