apiVersion: apps/v1
kind: Deployment
metadata:
  name: vault-agent
  namespace: vault
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vault-agent
  template:
    metadata:
      labels:
        app: vault-agent
    spec:
      serviceAccountName: vault-sa
      automountServiceAccountToken: false
      securityContext:
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
      initContainers:
      - name: fix-permissions
        image: busybox
        command: ["sh", "-c", "chown -R 1000:1000 /mnt/data/vault-agent"]
        volumeMounts:
        - name: vault-agent-storage
          mountPath: /mnt/data/vault-agent
        securityContext:
          runAsUser: 0

      containers:
      - name: vault-agent
        image: hashicorp/vault:1.15.0
        imagePullPolicy: Always
        args:
          - "agent"
          - "-config=/vault/config/vault-agent-config.hcl"
        env:
        - name: VAULT_ADDR
          value: "http://vault:8200"
        ports:
        - containerPort: 8200
        volumeMounts:
        - name: vault-agent-storage
          mountPath: /mnt/data/vault-agent
        - name: vault-config
          mountPath: /vault/config
          readOnly: true
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /v1/sys/health?standbyok=true&sealedcode=200
            port: 8200
          initialDelaySeconds: 60
          periodSeconds: 20
        readinessProbe:
          httpGet:
            path: /v1/sys/health?standbyok=true&sealedcode=200
            port: 8200
          initialDelaySeconds: 60
          periodSeconds: 20
        securityContext:
          runAsUser: 1000
          runAsGroup: 1000
          allowPrivilegeEscalation: false
          capabilities:
            drop:
              - ALL

      volumes:
      - name: vault-agent-storage
        persistentVolumeClaim:
          claimName: vault-agent-pvc
      - name: vault-config
        configMap:
          name: vault-agent-config
