apiVersion: apps/v1
kind: Deployment
metadata:
  name: vault-agent
  namespace: vault
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vault-agent
  template:
    metadata:
      labels:
        app: vault-agent
    spec:
      serviceAccountName: vault-sa
      initContainers:
        - name: create-token-dir
          image: busybox
          command: ["sh", "-c", "mkdir -p /mnt/data/vault-agent"]
          volumeMounts:
            - name: token
              mountPath: /mnt/data
      containers:
        - name: vault-agent
          image: hashicorp/vault:1.15.0
          command: ["vault", "agent", "-config=/vault/config/vault-agent-config.hcl", "-log-level=debug"]
          securityContext:
            capabilities:
              add: ["IPC_LOCK"]
          volumeMounts:
            - name: config
              mountPath: /vault/config
              readOnly: true
            - name: token
              mountPath: /mnt/data
      volumes:
        - name: config
          configMap:
            name: vault-agent-config
        - name: token
          emptyDir: {}
