apiVersion: apps/v1
kind: Deployment
metadata:
  name: vault
  namespace: vault
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vault
  template:
    metadata:
      labels:
        app: vault
    spec:
      serviceAccountName: vault-sa
      automountServiceAccountToken: false
      securityContext:
        fsGroup: 1000
      initContainers:
        - name: fix-permissions
          image: alpine:3.18
          command:
            - /bin/sh
            - -c
            - |
              # Set permissions for /vault/config
              chmod -R 755 /vault/config || echo "warn: chmod fail"
              # Ensure the vault.hcl file has correct permissions
              chmod 644 /vault/config/vault.hcl || echo "warn: chmod fail"
          securityContext:
            runAsUser: 1000
            runAsGroup: 1000
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
          volumeMounts:
            - name: configmap-copy
              mountPath: /vault/config

        - name: copy-config
          image: alpine:3.18
          command:
            - /bin/sh
            - -c
            - |
              mkdir -p /vault/config
              cp /source/vault.hcl /vault/config/vault.hcl
              chmod 644 /vault/config/vault.hcl
              ls -l /vault/config  # Check if the file is copied
              cat /vault/config/vault.hcl  # View the contents of vault.hcl
              sleep 30  # Keep the container running for debugging
          securityContext:
            runAsUser: 1000
            runAsGroup: 1000
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
          volumeMounts:
            - name: configmap-readonly
              mountPath: /source
              readOnly: true
            - name: configmap-copy
              mountPath: /vault/config

      containers:
        - name: vault
          image: hashicorp/vault:1.15.0
          args:
            - "server"
            - "-config=/vault/config/vault.hcl"
          env:
            - name: VAULT_API_ADDR
              value: http://0.0.0.0:8200
            - name: VAULT_ADDR
              value: http://127.0.0.1:8200
          ports:
            - containerPort: 8200
          volumeMounts:
            - name: vault-storage
              mountPath: /vault/data
            - name: configmap-copy
              mountPath: /vault/config  # Allow write access
          resources:
            requests:
              memory: "512Mi"
              cpu: "500m"
            limits:
              memory: "1Gi"
              cpu: "1"
          livenessProbe:
            httpGet:
              path: /v1/sys/health?standbyok=true&sealedcode=200
              port: 8200
            initialDelaySeconds: 30
            periodSeconds: 20
          readinessProbe:
            httpGet:
              path: /v1/sys/health?standbyok=true&sealedcode=200
              port: 8200
            initialDelaySeconds: 30
            periodSeconds: 20
          securityContext:
            runAsUser: 1000
            runAsGroup: 1000
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL

      volumes:
        - name: vault-storage
          hostPath:
            path: /mnt/vault-data
            type: DirectoryOrCreate
        - name: configmap-readonly
          configMap:
            name: vault-config1
            items:
              - key: vault.hcl
                path: vault.hcl
        - name: configmap-copy
          emptyDir: {}  # Allow write access here
