apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/instance: vault
  name: vault
  namespace: vault
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vault
  template:
    metadata:
      labels:
        app: vault
    spec:
      automountServiceAccountToken: false
      serviceAccountName: vault-sa
      securityContext:
        fsGroup: 1000
        runAsGroup: 1000
        runAsUser: 1000
      containers:
        - name: vault
          image: hashicorp/vault:1.15.0
          imagePullPolicy: Always
          args:
            - server
            - '-config=/vault/config/vault.hcl'
          env:
            - name: VAULT_ADDR
              value: http://127.0.0.1:8200
            - name: VAULT_USER
              value: vaultuser
            - name: VAULT_PASSWORD
              value: vaultpass
          ports:
            - containerPort: 8200
          volumeMounts:
            - mountPath: /vault/data
              name: vault-storage
            - mountPath: /vault/config
              name: config
          resources:
            limits:
              cpu: '1'
              memory: 1Gi
            requests:
              cpu: 500m
              memory: 512Mi
          livenessProbe:
            httpGet:
              path: /v1/sys/health?standbyok=true&sealedcode=200
              port: 8200
            initialDelaySeconds: 180
            periodSeconds: 20
          readinessProbe:
            httpGet:
              path: /v1/sys/health?standbyok=true&sealedcode=200
              port: 8200
            initialDelaySeconds: 180
            periodSeconds: 20
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
            runAsGroup: 1000
            runAsUser: 1000
      initContainers:
        - name: fix-permissions
          image: busybox
          command:
            - sh
            - '-c'
            - chown -R 1000:1000 /mnt/vault-data
          volumeMounts:
            - mountPath: /mnt/vault-data
              name: vault-storage
      volumes:
        - name: vault-storage
          persistentVolumeClaim:
            claimName: vault-pvc-new
        - name: config
          configMap:
            name: vault-config4
