apiVersion: apps/v1
kind: Deployment
metadata:
  name: vault-agent
  namespace: vault
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vault-agent
  template:
    metadata:
      labels:
        app: vault-agent
    spec:
      serviceAccountName: vault-sa
      securityContext:
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
      containers:
        - name: vault-agent
          image: hashicorp/vault:1.15.0
          imagePullPolicy: Always
          args:
            - "agent"
            - "-config=/vault/config/vault-agent-config.hcl"
          env:
            - name: VAULT_ADDR
              value: "http://vault:8200"
          ports:
            - containerPort: 8200
          volumeMounts:
            - name: vault-config
              mountPath: /vault/config
              readOnly: true  # ConfigMap is read-only
            - name: vault-agent-storage
              mountPath: /mnt/data/vault-agent  # Writable volume
        initContainers:
          - name: fix-permissions
            image: busybox
            imagePullPolicy: Always
            command:
              - sh
              - -c
              - chown -R 1000:1000 /mnt/data/vault-agent  # Apply chown to writable volume
            securityContext:
              runAsUser: 0
            volumeMounts:
              - name: vault-agent-storage
                mountPath: /mnt/data/vault-agent
      volumes:
        - name: vault-config
          configMap:
            name: vault-agent-config  # The ConfigMap holding the vault-agent-config.hcl file
        - name: vault-agent-storage
          persistentVolumeClaim:
            claimName: vault-agent-pvc  # Ensure PVC is not read-only
