apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/instance: vault
  name: vault
  namespace: vault
spec:
  replicas: 1
  progressDeadlineSeconds: 600 # Increased progress deadline
  selector:
    matchLabels:
      app: vault
  template:
    metadata:
      labels:
        app: vault
    spec:
      automountServiceAccountToken: false
      serviceAccountName: vault-sa
      securityContext:
        fsGroup: 1000
        runAsGroup: 1000
        runAsUser: 1000
        allowPrivilegeEscalation: false
        readOnlyRootFilesystem: false  # Allow write access to the filesystem
      containers:
        - name: vault
          image: hashicorp/vault:1.15.0
          imagePullPolicy: Always
          args:
            - server
            - '-config=/vault/config/vault.hcl'
          env:
            - name: SKIP_CHOWN
              value: "true"
            - name: VAULT_API_ADDR
              value: http://0.0.0.0:8200
            - name: VAULT_ADDR
              value: http://127.0.0.1:8200
            - name: VAULT_USER
              value: vaultuser
            - name: VAULT_PASSWORD
              value: vaultpass
          ports:
            - containerPort: 8200
          volumeMounts:
            - mountPath: /vault/data
              name: vault-storage
            - mountPath: /vault/config
              name: config
          resources:
            limits:
              cpu: "500m"
              memory: 512Mi
            requests:
              cpu: 250m
              memory: 256Mi
          livenessProbe:
            httpGet:
              path: /v1/sys/health?standbyok=true&sealedcode=200
              port: 8200
            initialDelaySeconds: 180
            periodSeconds: 20
          readinessProbe:
            httpGet:
              path: /v1/sys/health?standbyok=true&sealedcode=200
              port: 8200
            initialDelaySeconds: 180
            periodSeconds: 20
      volumes:
        - name: vault-storage
          persistentVolumeClaim:
            claimName: vault-agent-pvc
        - name: config
          configMap:
            name: vault-config
