apiVersion: v1
kind: PersistentVolume
metadata:
  name: vault-agent-pv
  namespace: vault
spec:
  capacity:
    storage: 1Gi  # Adjust the storage size if necessary
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: gp3-csi  # Use your storage class if different
  hostPath:
    path: /mnt/data/vault-agent  # Choose a valid path on your nodes, or use cloud-based volumes like EBS
