apiVersion: apps/v1
kind: Deployment
metadata:
  name: vault-agent
  namespace: vault
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vault-agent
  template:
    metadata:
      labels:
        app: vault-agent
    spec:
      containers:
        - name: vault-agent
          image: hashicorp/vault:1.15.0
          volumeMounts:
            - name: vault-agent-storage
              mountPath: /mnt/data/vault-agent
            - name: vault-config
              mountPath: /vault/config
      volumes:
        - name: vault-agent-storage
          persistentVolumeClaim:
            claimName: vault-agent-pvc
        - name: vault-config
          configMap:
            name: vault-agent-config
