apiVersion: v1
kind: PersistentVolume
metadata:
  name: vault-pv-new
spec:
  capacity:
    storage: 1Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: gp3-csi
  csi:
    driver: ebs.csi.aws.com
    volumeHandle: vol-020ca945a682db599  # Your AWS EBS Volume ID
