apiVersion: apps/v1
kind: Deployment
metadata:
  name: vault
  namespace: vault
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vault
  template:
    metadata:
      labels:
        app: vault
    spec:
      serviceAccountName: vault-sa
      automountServiceAccountToken: false
      securityContext:
        fsGroup: 1000  # Set the group ID for shared access
      initContainers:
        - name: fix-permissions
          image: alpine:3.18
          command:
            - /bin/sh
            - -c
            - |
              chmod -R 755 /vault/config || echo "warn: chmod fail"
          securityContext:
            runAsUser: 0  # Run as root for fixing permissions
            runAsGroup: 0 # Root group
            allowPrivilegeEscalation: true
            capabilities:
              add:
                - DAC_OVERRIDE  # Allow overriding file system ACLs
                - CHOWN  # Allow changing file ownership
          volumeMounts:
            - name: configmap-copy
              mountPath: /vault/config

        - name: copy-config
          image: alpine:3.18
          command:
            - /bin/sh
            - -c
            - |
              mkdir -p /vault/config
              cp /source/vault.hcl /vault/config/vault.hcl
              chmod 644 /vault/config/vault.hcl
              ls -l /vault/config  # Check if the file is copied
              sleep 30  # Keep the container running for debugging
          securityContext:
            runAsUser: 0  # Run as root to copy file and set permissions
            runAsGroup: 0 # Root group
            allowPrivilegeEscalation: true
            capabilities:
              add:
                - DAC_OVERRIDE  # Allow overriding file system ACLs
                - CHOWN  # Allow changing file ownership
          volumeMounts:
            - name: configmap-readonly
              mountPath: /source
              readOnly: true
            - name: configmap-copy
              mountPath: /vault/config

      containers:
        - name: vault
          image: hashicorp/vault:1.15.0
          args:
            - "server"
            - "-config=/vault/config/vault.hcl"
          env:
            - name: VAULT_API_ADDR
              value: http://0.0.0.0:8200
            - name: VAULT_ADDR
              value: http://127.0.0.1:8200
          ports:
            - containerPort: 8200
          volumeMounts:
            - name: vault-storage
              mountPath: /vault/data
            - name: configmap-copy
              mountPath: /vault/config
              readOnly
