apiVersion: v1
kind: ConfigMap
metadata:
  name: vault-agent-config
  namespace: vault
data:
  vault-agent-config.hcl: |
    pid_file = "/tmp/vault-agent-pid"

    auto_auth {
      method "kubernetes" {
        mount_path = "auth/kubernetes"
        config = {
          role = "vault-role"
        }
      }

      sink "file" {
        config = {
          path = "/home/vault/.vault-token"
        }
      }
    }
