apiVersion: apps/v1
kind: Deployment
metadata:
  name: vault-agent
  namespace: vault
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vault-agent
  template:
    metadata:
      labels:
        app: vault-agent
    spec:
      serviceAccountName: vault-sa
      containers:
      - name: vault-agent
        image: hashicorp/vault:1.15.0
        imagePullPolicy: Always
        args:
          - "agent"
          - "-config=/vault/config/vault-agent-config.hcl"
        ports:
        - containerPort: 8200
        env:
        - name: VAULT_ADDR
          value: "http://vault:8200"
        volumeMounts:
        - name: vault-config
          mountPath: /vault/config
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /v1/sys/health?standbyok=true&sealedcode=200
            port: 8200
          initialDelaySeconds: 60
          periodSeconds: 20
        readinessProbe:
          httpGet:
            path: /v1/sys/health?standbyok=true&sealedcode=200
            port: 8200
          initialDelaySeconds: 60
          periodSeconds: 20
        securityContext:
          runAsUser: 1000
          runAsGroup: 1000
          allowPrivilegeEscalation: false
          capabilities:
            drop:
              - ALL
      volumes:
      - name: vault-config
        configMap:
          name: vault-agent-config
